// Run with an extracted @tabler/icons@3.48.0 package directory.
import assert from 'node:assert/strict';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { format } from 'prettier';
import { commonTablerIcons } from '../src/commonTablerIcons.ts';
const directory = resolve(process.argv[2] ?? '.dev/tabler/package');
const read = async (file) =>
  JSON.parse(await readFile(join(directory, file), 'utf8'));
const pkg = await read('package.json');
assert.equal(pkg.name, '@tabler/icons');
assert.equal(pkg.version, '3.48.0');
const nodes = await read('tabler-nodes-outline.json');
const metadata = await read('icons.json');
const overrides = new Map(commonTablerIcons.map((icon) => [icon.id, icon]));
const catalog = [],
  paths = {};
for (const id of Object.keys(nodes).sort()) {
  assert.match(id, /^[a-z0-9-]+$/);
  assert.ok(metadata[id]?.styles.outline, `Missing outline metadata: ${id}`);
  paths[id] = nodes[id].map(([tag, attrs]) => {
    assert.equal(tag, 'path', `Unsupported shape: ${id}`);
    assert.ok(typeof attrs.d === 'string' && attrs.d.length > 0);
    for (const key of Object.keys(attrs))
      assert.ok(['d', 'fill', 'stroke', 'opacity'].includes(key));
    if (attrs.fill !== undefined) assert.equal(attrs.fill, 'currentColor');
    if (attrs.stroke !== undefined) assert.equal(attrs.stroke, 'none');
    if (attrs.opacity !== undefined)
      assert.ok(Number(attrs.opacity) >= 0 && Number(attrs.opacity) <= 1);
    return {
      ...attrs,
      ...(attrs.opacity === undefined
        ? {}
        : { opacity: Number(attrs.opacity) }),
    };
  });
  assert.ok(paths[id].length);
  const common = overrides.get(id);
  catalog.push({
    id,
    label:
      common?.label ??
      id
        .split('-')
        .map((word) => word[0].toUpperCase() + word.slice(1))
        .join(' '),
    tags: [
      ...new Set([
        ...(metadata[id].tags ?? []),
        metadata[id].category,
        common?.tags,
      ]),
    ]
      .filter(Boolean)
      .join(' '),
  });
}
assert.equal(catalog.length, 5166);
assert.equal(
  (await readdir(join(directory, 'icons/outline'))).filter((file) =>
    file.endsWith('.svg'),
  ).length,
  catalog.length,
);
for (const id of overrides.keys())
  assert.ok(paths[id], `Missing common icon: ${id}`);
const header =
  '// Generated by scripts/generate-tabler.mjs from @tabler/icons 3.48.0.\n// MIT: docs/licenses/TABLER_LICENSE.txt. Retain stable IDs for saved habits.\n';
for (const [name, source] of [
  [
    'tablerIconCatalog.ts',
    `export const tablerIconCatalog = ${JSON.stringify(catalog)} as const;\n`,
  ],
  [
    'tablerPaths.ts',
    `export type TablerPath = { d: string; fill?: 'currentColor'; stroke?: 'none'; opacity?: number };\nexport const tablerPaths: Record<string, TablerPath[]> = ${JSON.stringify(paths)};\n`,
  ],
])
  await writeFile(
    new URL(`../src/${name}`, import.meta.url),
    await format(header + source, { parser: 'typescript', singleQuote: true }),
  );
await writeFile(
  new URL('../docs/licenses/TABLER_LICENSE.txt', import.meta.url),
  await readFile(join(directory, 'LICENSE')),
);
console.log(`Generated ${catalog.length} Tabler outline icons and metadata.`);
