// Generated by scripts/generate-editor-icons.mjs from the bundled Tabler Outline 3.48.0 paths.
// MIT: docs/licenses/TABLER_LICENSE.txt.
export const editorIconPaths = {
  undo: [{ d: 'M9 14l-4 -4l4 -4' }, { d: 'M5 10h11a4 4 0 1 1 0 8h-1' }],
  redo: [{ d: 'M15 14l4 -4l-4 -4' }, { d: 'M19 10h-11a4 4 0 1 0 0 8h1' }],
  bold: [
    { d: 'M7 5h6a3.5 3.5 0 0 1 0 7h-6l0 -7' },
    { d: 'M13 12h1a3.5 3.5 0 0 1 0 7h-7v-7' },
  ],
  italic: [{ d: 'M11 5l6 0' }, { d: 'M7 19l6 0' }, { d: 'M14 5l-4 14' }],
  text: [
    { d: 'M4 20l3 0' },
    { d: 'M14 20l7 0' },
    { d: 'M6.9 15l6.9 0' },
    { d: 'M10.2 6.3l5.8 13.7' },
    { d: 'M5 20l6 -16l2 0l7 16' },
  ],
  link: [
    { d: 'M9 15l6 -6' },
    { d: 'M11 6l.463 -.536a5 5 0 0 1 7.071 7.072l-.534 .464' },
    {
      d: 'M13 18l-.397 .534a5.068 5.068 0 0 1 -7.127 0a4.972 4.972 0 0 1 0 -7.071l.524 -.463',
    },
  ],
  highlight: [
    { d: 'M3 19h4l10.5 -10.5a2.828 2.828 0 1 0 -4 -4l-10.5 10.5v4' },
    { d: 'M12.5 5.5l4 4' },
    { d: 'M4.5 13.5l4 4' },
    { d: 'M21 15v4h-8l4 -4l4 0' },
  ],
  heading: [
    {
      d: 'M17 12a2 2 0 1 1 4 0c0 .591 -.417 1.318 -.816 1.858l-3.184 4.143l4 0',
    },
    { d: 'M4 6v12' },
    { d: 'M12 6v12' },
    { d: 'M11 18h2' },
    { d: 'M3 18h2' },
    { d: 'M4 12h8' },
    { d: 'M3 6h2' },
    { d: 'M11 6h2' },
  ],
  bullets: [
    { d: 'M9 6l11 0' },
    { d: 'M9 12l11 0' },
    { d: 'M9 18l11 0' },
    { d: 'M5 6l0 .01' },
    { d: 'M5 12l0 .01' },
    { d: 'M5 18l0 .01' },
  ],
  numbered: [
    { d: 'M11 6h9' },
    { d: 'M11 12h9' },
    { d: 'M12 18h8' },
    { d: 'M4 16a2 2 0 1 1 4 0c0 .591 -.5 1 -1 1.5l-3 2.5h4' },
    { d: 'M6 10v-6l-2 2' },
  ],
  quote: [
    { d: 'M6 15h15' },
    { d: 'M21 19h-15' },
    { d: 'M15 11h6' },
    { d: 'M21 7h-6' },
    { d: 'M9 9h1a1 1 0 1 1 -1 1v-2.5a2 2 0 0 1 2 -2' },
    { d: 'M3 9h1a1 1 0 1 1 -1 1v-2.5a2 2 0 0 1 2 -2' },
  ],
  strike: [
    { d: 'M5 12l14 0' },
    {
      d: 'M16 6.5a4 2 0 0 0 -4 -1.5h-1a3.5 3.5 0 0 0 0 7h2a3.5 3.5 0 0 1 0 7h-1.5a4 2 0 0 1 -4 -1.5',
    },
  ],
  code: [{ d: 'M7 8l-4 4l4 4' }, { d: 'M17 8l4 4l-4 4' }, { d: 'M14 4l-4 16' }],
  clear: [
    { d: 'M17 15l4 4m0 -4l-4 4' },
    { d: 'M7 6v-1h11v1' },
    { d: 'M7 19l4 0' },
    { d: 'M13 5l-4 14' },
  ],
} as const;
export type EditorIconName = keyof typeof editorIconPaths;
