export type Habit = { id: string; name: string; color: string; unit?: string };

export const habitColors = [
  { name: 'Mint', value: '#82E6BC' },
  { name: 'Lavender', value: '#BDA5FF' },
  { name: 'Sky', value: '#84C9FF' },
  { name: 'Peach', value: '#FFB38A' },
  { name: 'Rose', value: '#FF9ABD' },
  { name: 'Lime', value: '#C5E788' },
  { name: 'Aqua', value: '#7DDDD9' },
  { name: 'Gold', value: '#F6D780' },
  { name: 'Coral', value: '#FF8F86' },
  { name: 'Orange', value: '#FFAB63' },
  { name: 'Lemon', value: '#EBE36F' },
  { name: 'Leaf', value: '#9CD978' },
  { name: 'Jade', value: '#64D7A2' },
  { name: 'Teal', value: '#56CBC4' },
  { name: 'Cyan', value: '#6CDCF2' },
  { name: 'Blue', value: '#8AAEFF' },
  { name: 'Periwinkle', value: '#A6ACFF' },
  { name: 'Violet', value: '#C394F5' },
  { name: 'Orchid', value: '#E29CE8' },
  { name: 'Pink', value: '#ED8DC3' },
  { name: 'Sand', value: '#D9C6AA' },
  { name: 'Silver', value: '#BFC8D4' },
  { name: 'Cloud', value: '#E3E7EE' },
  { name: 'White', value: '#FFFFFF' },
];

export const demoHabits: Habit[] = [
  { id: 'walk', name: 'Go for a walk', color: '#82E6BC' },
  { id: 'read', name: 'Read', unit: 'minutes', color: '#BDA5FF' },
  { id: 'water', name: 'Drink water', unit: 'glasses', color: '#84C9FF' },
  { id: 'stretch', name: 'Stretch', color: '#FFB38A' },
  { id: 'journal', name: 'Write a little', color: '#FF9ABD' },
  { id: 'outside', name: 'Get outside', color: '#C5E788' },
  { id: 'meditate', name: 'Meditate', color: '#7DDDD9' },
  { id: 'cook', name: 'Cook a meal', color: '#F6D780' },
  { id: 'tidy', name: 'Tidy up', color: '#82E6BC' },
  { id: 'connect', name: 'Call someone', color: '#BDA5FF' },
  { id: 'learn', name: 'Learn something', color: '#84C9FF' },
  { id: 'sleep', name: 'Wind down', color: '#FFB38A' },
];
